#!/bin/bash

# Color definitions
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
B="$(printf '\033[1;34m')"
C="$(printf '\033[1;36m')"
W="$(printf '\033[1;37m')"
BOLD="$(printf '\033[1m')"

# Clear the screen
clear

# Download the server check script
server_script_url="https://raw.githubusercontent.com/wa-inc/Sm_Lator/main/SmLator/server.py"
server_script_path="$PREFIX/bin/server.py"
curl -s -o "$server_script_path" "$server_script_url"
chmod +x "$server_script_path"

# Start DARKOS
start_darkos() {
    # Clear the screen
    clear

    # Remove LD_PRELOAD environment variable if it exists
    if [[ -n "$LD_PRELOAD" ]]; then
        unset LD_PRELOAD
    fi

    # Check server status
    if ! python3 "$server_script_path"; then
        sleep 3
        termux-exit
        exit 1
    fi

    # Print starting message
    echo "${G}[${W}-${G}] Starting ${W}"

    # Start Termux X11 and PulseAudio
    termux-x11 :0 &>/dev/null &
    pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
}

# Run the Python script
python3 $PREFIX/bin/photo.py "$@"

# Prompt for Safe Mode
echo "${G}${BOLD} PRESS 1 TO ENTER SAFE MODE ....... ${W}"
read -t 2 -n1 -s key

# Safe Mode handling
if [[ "$key" == "1" ]]; then
    echo "${G}${BOLD} Safe MODE SmLator.....STARTING${W}"
    termux-x11 :0 &>/dev/null &
    pkill -9 pulseaudio 
    if [[ -f "/system/lib64/libskcodec.so" ]] ; then
        LD_PRELOAD="/system/lib64/libskcodec.so" pulseaudio --start --exit-idle-time=-1 &
        sleep 1
        pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1 
    else
        pulseaudio --start --exit-idle-time=-1 &
        sleep 1
        pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
    fi
    python3 $PREFIX/bin/darkos.py "$@"
    exit 0
elif [[ "$key" == " " ]]; then
    echo "${G}${BOLD} Booting SmLator 🖤 ${W}"
fi

# Check for updates
old_version="0.971"
new_version=$(curl -s https://raw.githubusercontent.com/ahmad1abbadi/darkos/main/currently%20version.txt)

if ping -q -c 1 -W 1 google.com >/dev/null; then
    echo "${G}${BOLD} Welcome to SmLator${W}"
    if awk 'BEGIN{exit !('$old_version' < '$new_version')}'; then
        echo ""
        echo "${G}${BOLD} Update available ⏫....to version : ${C}${BOLD}$new_version${W}"
        sleep 3
    else
        echo "${G}${BOLD} Installed version : ${C}${BOLD}$old_version${W}"
        sleep 1
    fi
else
    echo "${G}${BOLD} No internet connection 😔🛜${W}"
fi

# Boot DARKOS
start_darkos

# Custom theme handling
custom_darkos="$PREFIX/glibc/opt/darkos/custom_theme.txt"

if [[ -f "$custom_darkos" ]]; then
    export DISPLAY=:0
    startxfce4 &>/dev/null &
    python3 $PREFIX/glibc/opt/scripts/custom_style.py "$@"
else
    python3 $PREFIX/bin/run-darkos.py "$@"
fi
